name: Patch APK using apk-mitm

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  patch-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install apk-mitm
      run: npm install -g apk-mitm

    - name: Download latest apktool
      run: |
        curl -L -o apktool.jar 'https://github.com/iBotPeaches/Apktool/releases/download/v2.12.0/apktool_2.12.0.jar'
        
    - name: Download APK
      run: |
        echo "Downloading APK..."
        curl -L -o base.apk 'https://files.catbox.moe/uzl6jg.apk⏎'
        
    - name: Patch APK with latest apktool and --no-crunch
      run: apk-mitm --apktool ./apktool.jar --no-crunch base.apk patched-base.apk

    - name: Upload patched APK
      uses: actions/upload-artifact@v4
      with:
        name: patched-base-apk
        path: base-patched.apk
